---
- name: Check if git is installed
  shell: command -v git >/dev/null 2>&1
  register: is_git_exist
  ignore_errors: yes

- name: Check if unzip is installed
  shell: command -v unzip >/dev/null 2>&1
  register: is_unzip_exist
  ignore_errors: yes

  # - name: Debug
  #   ansible.builtin.debug:
  #     var: is_git_exist
  #     # verbosity: 2

  # - name: Debug
  #   ansible.builtin.debug:
  #     var: is_unzip_exist
  #     # verbosity: 2
  #   when: is_unzip_exist is failed and is_git_exist is failed

- name: Fail becouse no git or unzip avaiable
  debug:
    msg: Fail becouse no git or unzip avaiable
  failed_when: is_unzip_exist is failed and is_git_exist is failed
  when: is_unzip_exist is failed and is_git_exist is failed

- name: Check nano version
  shell: nano --version | head -n1 | cut -d' ' -f5
  register: nano_version

- name: Set repo version to 2.9
  set_fact:
    repo_version: "2.9"
  when: nano_version.stdout | float <= 2.9

- name: Set repo version to master
  set_fact:
    repo_version: "master"
  when: nano_version.stdout | float > 2.9

- name: Check if XDG Directories are in use
  command: test -f $HOME/.nano || test -f $HOME/.nanorc
  register: no_xdg
  ignore_errors: yes
  when: not system_wide 

- name: Set single user installation path to XDG based
  set_fact:
    installation_path: $XDG_CONFIG_HOME/nano/_nanorc/
    nano_rc_file: $XDG_CONFIG_HOME/nanorc
  when: not no_xdg | bool

- name: Set single user installation path to legacy
  set_fact:
    installation_path: $HOME/.nano/
    nano_rc_file: $HOME/.nanorc
  when: no_xdg | bool

# - name: Proceed with git
#   debug:
#     msg: echo Proceed with git
#   when: is_git_exist is not failed and strategy == 'git'

- name: Proceed with git
  include_tasks: install_via_git.yml

- name: Proceed with unzip
  debug:
    msg: echo Proceed with unzip
  when: is_unzip_exist is not failed and strategy == 'zip'

- name: Enable installed files
  become: yes
  command: echo "include {{ system_wide_path }}/*.nanorc" >> /etc/nanorc
  when: system_wide

- name: Enable installed files
  command: echo "include {{ installation_path }}/*.nanorc" >> {{ nano_rc_file }}
  when: not system_wide